# Caution: this file may be regenerated by SOPC Builder.  User edits will be lost.
project_open -current_revision "C:/Users/tore/zylin/ecosboard/ecosboard/fw/nios_standard/cycloneIII_3c25_niosII_standard.qpf"
project_close