MAIN_DIR=`pwd`

export FLASH_BASE=0x4000000
export FLASH_END=0x5FFFFFF
export RESET_ADDRESS_FACTORY=0x4120000

export FACTORY_SOF_OFFSET=0X20000
export APPLICATION_SOF_OFFSET=0X200000
export BOOTLOADER_FLASH_OFFSET=0X120000
export DEFLATOR_FLASH_OFFSET=0X300000
export APPLICATION_FLASH_OFFSET=0X320000

export FACTORY_SOF=/home/laurentiu/workspace/zy1000/build/revc/cycloneIII_3c25_niosII_standard
export APPLICATION_SOF=/home/laurentiu/workspace/zy1000/build/revc/cycloneIII_3c25_niosII_standard
export ALTERA_BOOTLOADER=$SOPC_KIT_NIOS2/components/altera_nios2/boot_loader_cfi.srec


BOOTLOADER_SOF=upgradeboot
BOOTLOADER_APP=bootloader
DEFLATOR_APP=deflator
APPLICATION_APP1=application
APPLICATION_APP2=main
CONCAT_APP=upgradeapplication
OUTPUT=out

export BOOTLOADER=$MAIN_DIR/$BOOTLOADER_APP/$OUTPUT/$BOOTLOADER_APP
export BOOTLOADER_UPGRADE=$MAIN_DIR/$BOOTLOADER_APP/$OUTPUT/$BOOTLOADER_SOF
export DEFLATOR=$MAIN_DIR/$DEFLATOR_APP/$OUTPUT/$DEFLATOR_APP